geekshop/admins/urls.py
from django.urls import path
from .views import AdminIndexView, UserListView, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, OrdersListView, OrdersUpdateView

app_name = 'admins'

urlpatterns = [
    path('', AdminIndexView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='user_read'),
    path('users-create/', UserCreateView.as_view(), name='user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('category/', CategoryListView.as_view(), name='category_read'),
    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('product/', ProductListView.as_view(), name='product_read'),
    path('product-create/', ProductCreateView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_read'),
    path('orders-update/<int:pk>/', OrdersUpdateView.as_view(), name='orders_update'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/urls.py
from django.urls import path
from ordersapp.views import OrdersListView, OrdersCreateView, OrdersDetailView, OrdersUpdateView, OrdersDeleteView, \
    order_forming_complete, get_product_price

app_name = 'ordersapp'

urlpatterns = [
    path('', OrdersListView.as_view(), name='list'),
    path('create/', OrdersCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', OrdersDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', OrdersUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', OrdersDeleteView.as_view(), name='delete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/price/', get_product_price, name='product_price')
]

geekshop/ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNL'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'Формируется'),
        (SEND_TO_PROCEED, 'Отправлен в обработку'),
        (PROCEEDED, 'Обрабатывается'),
        (PAID, 'Оплачен'),
        (READY, 'Готов к выдаче'),
        (CANCEL, 'Отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='Статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    # TODO: take out self.orderitems.select_related()

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda i: i.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda i: i.get_product_cost(), items)))

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
            self.is_active = False
            self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='Заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    quantity = models.IntegerField(verbose_name='Количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

geekshop/ordersapp/forms.py
from django import forms
from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):

    price = forms.CharField(label='Цена', required=False)

    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OrderItemsForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

geekshop/ordersapp/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from baskets.models import Basket
from mainapp.mixin import BaseClassContextMixin
from mainapp.models import Product
from ordersapp.forms import OrderItemsForm
from ordersapp.models import Order, OrderItem


class OrdersListView(ListView, BaseClassContextMixin):
    model = Order
    template_name = 'ordersapp/order_list.html'
    title = 'GeekShop | Список заказов'


class OrdersCreateView(CreateView, BaseClassContextMixin):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')
    title = 'GeekShop | Оформить заказ'

    def get_context_data(self, **kwargs):
        context = super(OrdersCreateView, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)
        basket_items = Basket.objects.filter(user=self.request.user)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
            basket_items.delete()
        else:
            if basket_items:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=basket_items.count())
                formset = OrderFormSet()
                for count, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[count].product
                    form.initial['quantity'] = basket_items[count].quantity
                    form.initial['price'] = basket_items[count].product.price
            else:
                formset = OrderFormSet()
        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        if self.object.get_total_cost == 0:
            self.object.delete()

        return super(OrdersCreateView, self).form_valid(form)


class OrdersDetailView(DetailView, BaseClassContextMixin):
    model = Order
    title = 'GeekShop | Просмотр заказа'


class OrdersUpdateView(UpdateView, BaseClassContextMixin):
    model = Order
    fields = []
    success_url = reverse_lazy('ordersapp:list')
    title = 'GeekShop | Редактирование заказа'

    def get_context_data(self, **kwargs):
        context = super(OrdersUpdateView, self).get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price
        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if formset.is_valid():
                formset.instance = self.object
                formset.save()

        if self.object.get_total_cost == 0:
            self.object.delete()

        return super(OrdersUpdateView, self).form_valid(form)


class OrdersDeleteView(DeleteView, BaseClassContextMixin):
    model = Order
    success_url = reverse_lazy('ordersapp:list')
    title = 'GeekShop | Удаление заказа'


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()
    return HttpResponseRedirect(reverse('ordersapp:list'))


def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.get(pk=pk)
        if product:
            return JsonResponse({'price': product.price})
        return JsonResponse({'price': 0})


@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantity_update_save(sender, instance, **kwargs):
    if instance.pk:
        get_item = instance.get_item(int(instance.pk))
        instance.product.quantity -= instance.quantity - get_item
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantity_update_save(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()

geekshop/ordersapp/templates/ordersapp/order_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="text-center">
   <div class="category_delete">
       <div class="h1">Уверены, что хотите удалить?</div>
       {% include 'ordersapp/includes/inc_order_summary.html' %}
       <form action="{% url 'ordersapp:delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="btn btn-danger" type="submit" value="Удалить">
       </form>
       <button class="btn btn-success mt-4">
           <a href="{% url 'ordersapp:list' %}">Отмена</a>
       </button>
   </div>
</div>
{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}



{% block content %}
   {% include 'ordersapp/includes/inc_order_summary.html' %}
   <div class="basket_list">
       {% for item in object.orderitems.select_related %}
           <div class="basket_record">
               <img style="height: 150px" src="{{ item.product.image.url }}"
                    alt="{{ item.product.short_desc }}">
               <span class="category_name">
                   {{ item.product.category.name }}
               </span>
               <span class="product_name">{{ item.product.name }}</span>
               <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
               <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
               <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
           </div>
       {% endfor %}
   </div>
   {% include 'ordersapp/includes/inc_order_actions.html' %}

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    {% include 'ordersapp/includes/inc_order_summary.html' %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name == 'price' %}
                                    {% if not field.value %}
                                    {% else %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }} руб </span>
                                    {% endif %}
                                {% else %}
                                    {{ field }}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-success btn-round form-control last">Сохранить
            </button>
            {% include 'ordersapp/includes/inc_order_actions.html' %}
        </form>
    </div>

{% endblock %}

geekshop/ordersapp/templates/ordersapp/order_list.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block content %}
    <div class="text-center">
        <div class="h2 text-center head">
            Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}
        </div>
        <table class="table orders_list">
            <thead>
            <tr>
                <th>ID</th>
                <th>Создан</th>
                <th>Обновлен</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <td class="td1 orders_list">{{ item.pk }}</td>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a href="{% url 'ordersapp:detail' item.pk %}">
                                Посмотреть
                            </a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:update' item.pk %}">
                                    Редактировать
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'ordersapp:delete' item.pk %}">
                                    Удалить
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        <button class="btn btn-light btn-round">
            <a href="{% url 'index' %}">
                На главную
            </a>
        </button>
        <button class="btn btn-warning btn-round">
            <a href="{% url 'ordersapp:create' %}">
                Новый
            </a>
        </button>
    </div>
{% endblock %}