geekshop/admins/urls.py
from django.urls import path
from .views import AdminIndexView, UserListView, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, OrdersListView, OrdersUpdateView

app_name = 'admins'

urlpatterns = [
    path('', AdminIndexView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='user_read'),
    path('users-create/', UserCreateView.as_view(), name='user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('category/', CategoryListView.as_view(), name='category_read'),
    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('product/', ProductListView.as_view(), name='product_read'),
    path('product-create/', ProductCreateView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_read'),
    path('orders-update/<int:pk>/', OrdersUpdateView.as_view(), name='orders_update'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/admins/templates/admins/includes/siberia-bar.html
<div class="sb-sidenav-menu">
    <div class="nav">
        <div class="sb-sidenav-menu-heading">Приложения</div>
        <a class="nav-link" href="{% url 'admins:user_read' %}">
            <div class="sb-nav-link-icon">
                <i class="fas fa-users"></i>
            </div>
            Пользователи
        </a>
        <a class="nav-link" href="{% url 'admins:category_read' %}">
            <div class="sb-nav-link-icon">
                <i class="fas fa-shopping-basket"></i>
            </div>
            Категории
        </a>
        <a class="nav-link" href="{% url 'admins:product_read' %}">
            <div class="sb-nav-link-icon">
                <i class="fas fa-tshirt"></i>
            </div>
            Продукты
        </a>
        <a class="nav-link" href="{% url 'admins:orders_read' %}">
            <div class="sb-nav-link-icon">
                <i class="fas fa-tshirt"></i>
            </div>
            Заказы
        </a>
    </div>
</div>