geekshop/admins/urls.py
from django.urls import path
from .views import AdminIndexView, UserListView, UserCreateView, UserUpdateView, UserDeleteView, CategoryListView, \
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, OrdersListView, OrdersUpdateView

app_name = 'admins'

urlpatterns = [
    path('', AdminIndexView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='user_read'),
    path('users-create/', UserCreateView.as_view(), name='user_create'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('category/', CategoryListView.as_view(), name='category_read'),
    path('category-create/', CategoryCreateView.as_view(), name='category_create'),
    path('category-update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category-delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('product/', ProductListView.as_view(), name='product_read'),
    path('product-create/', ProductCreateView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrdersListView.as_view(), name='orders_read'),
    path('orders-update/<int:pk>/', OrdersUpdateView.as_view(), name='orders_update'),
]

geekshop/authapp/urls.py
from django.urls import path
from authapp.views import UserLoginView, UserRegisterView, UserLogoutView, ProfileView

app_name = 'authapp'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', UserRegisterView.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='ordersapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/ordersapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PROCEEDED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    CANCEL = 'CNL'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'Формируется'),
        (SEND_TO_PROCEED, 'Отправлен в обработку'),
        (PROCEEDED, 'Обрабатывается'),
        (PAID, 'Оплачен'),
        (READY, 'Готов к выдаче'),
        (CANCEL, 'Отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='Создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='Обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='Статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='Активный', default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    # TODO: take out self.orderitems.select_related()

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda i: i.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda i: i.get_product_cost(), items)))

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
            self.is_active = False
            self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='Заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='Продукт', on_delete=models.CASCADE)
    quantity = models.IntegerField(verbose_name='Количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity

geekshop/admins/templates/admins/admin-category-create.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Создание категории</h1>
            <form action="{% url 'admins:category_create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование категориии</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание категориии</label>
                            {{ form.description }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории продуктов</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование категории</th>
                                <th>Описание</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наименование категории</th>
                                <th>Описание</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:category_update' category.id %}"
                                           style="color: dodgerblue">{{ category.name }}</a>
                                    </td>
                                    <td>{{ category.description }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-category-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Изменение категории | {{ productcategory }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:category_update' productcategory.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование категории</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:category_delete' productcategory.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-orders-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Заказы</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>id Заказа</th>
                                <th>Пользователь</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Цена</th>
                                <th>Статус</th>
                                <th>Активность</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>id Заказа</th>
                                <th>Пользователь</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th>Цена</th>
                                <th>Статус</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for order in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:orders_update' order.id %}"
                                           style="color: dodgerblue">{{ order.id }}</a>
                                    </td>
                                    <td>{{ order.user }}</td>
                                    <td>{{ order.created|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.updated|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ order.get_total_cost }}&nbspруб</td>
                                    <td>{{ order.get_status_display }}</td>
                                    <td>
                                        {% if order.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:product_create' %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-orders-update.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Обновление заказа № {{ order.id }} пользователя {{ order.user }}</h1>
            <div class="card-body">
                <div class="basket_list">
                    {% for item in object.orderitems.select_related %}
                        <div class="basket_record">
                            <img style="height: 80px" src="{{ item.product.image.url }}"
                                 alt="{{ item.product.short_desc }}">
                            <span class="category_name">
                   {{ item.product.category.name }}
               </span>
                            <span class="product_name">{{ item.product.name }}</span>
                            <span class="product_price">
                   {{ item.product.price }}&nbspруб
               </span>
                            <span class="product_quantitiy">
                   x {{ item.quantity }} шт.
               </span>
                            <span class="product_cost">
                    = {{ item.get_product_cost }}&nbspруб
               </span>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <form action="{% url 'admins:orders_update' object.id %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.status.id_for_label }}">Статус заказа</label>
                            {{ form.status }}
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-product-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наименование товара</th>
                                <th>Категория</th>
                                <th>Краткое описание</th>
                                <th>Описание</th>
                                <th>Цена</th>
                                <th>Количество на складе</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наименование товара</th>
                                <th>Категория</th>
                                <th>Краткое описание</th>
                                <th>Описание</th>
                                <th>Цена</th>
                                <th>Количество на складе</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:product_update' product.id %}"
                                           style="color: dodgerblue">{{ product.name }}</a>
                                    </td>
                                    <td>{{ product.category }}</td>
                                    <td>{{ product.short_description }}</td>
                                    <td>{{ product.description }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:product_create' %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-product-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование | {{ product.name }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:product_update' product.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-lg-12 text-center">
                        <img width="400" height="400"
                             src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'vendor/img/products/default_product.png' %} {% endif %}"
                             class="img-thumbnail">
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Наименование товара</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория
                                    товара</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.short_description.id_for_label }}">Краткое
                                описание</label>
                            {{ form.short_description }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество на
                                складе</label>
                            {{ form.quantity }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:product_delete' product.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:user_update' user.id %}"
                                           style="color: dodgerblue">{{ user.username }}</a>
                                    </td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}</td>
                                    <td class="text-center">
                                        {% if user.is_active %}
                                            <i class="fas fa-check-circle"></i>
                                        {% else %}
                                            <i class="fas fa-times-circle"></i>
                                        {% endif %}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:user_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:user_update' user.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-lg-12 text-center">
                        <img width="400" height="400"
                             src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                             class="img-thumbnail">
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:user_delete' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

geekshop/admins/templates/admins/admin.html
{% extends 'admins/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Административная панель</h1>
        </div>
    </main>
{% endblock %}